#!/usr/bin/env python

# author: Neriberto C.Prado
# website: www.mundolivre.eti.br
# contact: neriberto[at]gmail[dot]com

import hashlib
import gtk
import sys


class PyApp(gtk.Window): 
  def __init__(self, filename):
    super(PyApp, self).__init__()

    self.set_size_request(400, 100)
    self.set_position(gtk.WIN_POS_CENTER)
    self.connect("destroy", gtk.main_quit)
    self.set_title("Hashes - %s" % filename)

    table = gtk.Table(2, 1, True);

    buffer=open(filename,"r").read()

    lblMD5 = gtk.Label("MD5: %s" % hashlib.md5(buffer).hexdigest() )
    lblSHA1 = gtk.Label("SHA1: %s" % hashlib.sha1(buffer).hexdigest() )

    # first line in table
    table.attach(lblMD5, 0, 1, 0, 1, gtk.EXPAND,gtk.EXPAND, 0, 0)
    # second line in table
    table.attach(lblSHA1, 0, 1, 1, 2, gtk.EXPAND, gtk.EXPAND, 0, 0)

    self.add(table)
    self.show_all()

if __name__=='__main__':
  PyApp(sys.argv[1])
  gtk.main()
